name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build binary(without output)
        run: deno compile -L debug main.ts

      - name: Build binary(with output)
        run: deno compile -L debug --output=build/helloworld main.ts
