name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build binary
        run: deno compile -L debug main.ts
      
      - name: Build binary
        run: deno compile -L debug --output=build/helloworld main.ts