name: Build
on:
  push:
  workflow_dispatch:

jobs:
  post_job:
    runs-on: ubuntu-latest

    steps:
      - name: post job 
        run: echo "This is post job"

  build:
    needs: post_job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            x86_64-unknown-linux-gnu,
            x86_64-pc-windows-msvc,
            x86_64-apple-darwin,
            aarch64-apple-darwin,
          ]

    steps:
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build binary(without output)
        run: deno compile -L debug main.ts
      
      - name: Build binary(with output)
        run: deno compile -L debug --output=build/helloworld main.ts
      
      - name: Build binary(with target + without output)
        run: deno compile -L debug --target=${{ matrix.target }} main.ts

      - name: Build binary(with target + with output)
        run: deno compile -L debug --target=${{ matrix.target }} --output=build/helloworld main.ts